# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JPDynamic' do

  # Pods for JPDynamic
  pod 'JRSwizzle', '~> 1.0'

  target 'JPDynamicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JPDynamicUITests' do
    # Pods for testing
  end

end
