# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'HBullShares' do

  pod 'AFNetworking'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'YYModel'
  pod 'MJRefresh'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
