platform :ios, '10.0'

inhibit_all_warnings!

workspace 'iRead.xcworkspace'


# debug_pods
def debug_pods
  pod 'FLEX', :configurations => ['Debug']
end

# common_pods
def common_pods
  pod 'IRHexColor', '~> 0.0.1'
  pod 'AEXML', '~> 4.5.0'
  pod 'SSZipArchive', '~> 2.2.2'
end

# common_pods
common_pods

# ==================================== Targets ==================================== #

target 'iRead' do

  # debug pods
  debug_pods
  

end

target 'IRCommonLib' do
  project 'IRCommonLib/IRCommonLib.xcodeproj'

end

# https://github.com/CocoaPods/CocoaPods/issues/8069
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
    end
end
